apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: obsidian-sync
data:
  local.ini: |
    [httpd]
    enable_cors = true

    [chttpd]
    bind_address = any

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    methods = GET, PUT, POST, HEAD, DELETE
    headers = accept, authorization, content-type, origin, referer
