apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-data-pvc
  namespace: radio-recorder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 100Gi  # pv.yaml の capacity と合わせること
